import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Footer from "../../components/Footer/Footer";
import Header from "../../components/Header/Header";
import HeaderWithText from "../../components/HeaderWithText/HeaderWithText";
import { HeadingDiv, SVGDiv } from "./style";

const AboutUs: NextPage = () => {
  return (
    <>
      <Head>
        <title>Pizza Mania</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <HeadingDiv>ABOUT US</HeadingDiv>

      <SVGDiv>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
          <path
            fill="#0099ff"
            fillOpacity="0.3"
            d="M0,64L40,85.3C80,107,160,149,240,170.7C320,192,400,192,480,170.7C560,149,640,107,720,106.7C800,107,880,149,960,181.3C1040,213,1120,235,1200,234.7C1280,235,1360,213,1400,202.7L1440,192L1440,0L1400,0C1360,0,1280,0,1200,0C1120,0,1040,0,960,0C880,0,800,0,720,0C640,0,560,0,480,0C400,0,320,0,240,0C160,0,80,0,40,0L0,0Z"
          ></path>
        </svg>
      </SVGDiv>
      <HeaderWithText
        title="Pizza Man: Delivering Happiness"
        desc="With Pizza Man it is always “Rishton ka time”. Whether it's a treat for your promotion, a kid topping his class or winning the heart of your wife who is too tired to cook after a long day at work! A cheesy slice of the best pizza is all one needs to put things into perspective and start any celebration. Plus, you do not even need to rush to the restaurant to have one now. A call, a few clicks on our website or a few touches on the mobile screen is all you have to do to have that tempting, light-on-the-pocket pizza at your doorstep."
      ></HeaderWithText>

      <HeaderWithText
        title="The Promise Of 30-Minute Delivery"
        desc="The icing on the cake or more aptly the extra cheese on your already fabulous pizza is that Pizza Man takes only half an hour for its pizza delivery service. Don’t believe us? Time it if you please. With 1250+ stores present all over India, you can have a Pizza Man pizza even while traveling on a train. Yes, you are reading it right, you can enjoy pizza on train too."
      ></HeaderWithText>

      <HeaderWithText
        title="Franchise Information"
        desc="We have come across a few instances of fraudsters posing as Tap FoodWorks and asking for payment from gullible investors against the promise of a Pizza Man franchise. We therefore caution and urge all interested parties to be careful and vigilant and interact only with the email id mentioned above. Anyone dealing with such fraudsters shall be doing so on their own peril, risk and consequences."
      ></HeaderWithText>

      <Footer />
    </>
  );
};

export default AboutUs;
