import React, { useEffect, useState } from "react";
import type { NextPage } from "next";
import Header from "../../components/Header/Header";
import Footer from "../../components/Footer/Footer";
import { Card, GridWrapper } from "./style";
import axios from "axios";
import Head from "next/head";

const Posts: NextPage = () => {
  const [data, setData] = useState<any>([]);

  useEffect(() => {
    axios.get("http://localhost:4000/posts").then((res) => {
      console.log(res);
      setData(res.data);
    });
  }, []);

  return (
    <>
      <Head>
        <title>Pizza Mania</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <GridWrapper>
        {data.map((item: any) => {
          return (
            <Card key={item.id}>
              <p>{item.title}</p>
              <br />
              <p>{item.author}</p>
            </Card>
          );
        })}
      </GridWrapper>
      <Footer />
    </>
  );
};

export default Posts;
